mlp:
    vars:
    - eta
    - lead_eta
    - lead_phi
    - Res_pholead_PtOverM
    - sublead_eta
    - sublead_phi
    - Res_phosublead_PtOverM
    - Res_lead_bjet_eta
    - Res_lead_bjet_phi
    - Res_lead_bjet_btagPNetB
    - Res_sublead_bjet_eta
    - Res_sublead_bjet_phi
    - Res_sublead_bjet_btagPNetB
    - Res_DeltaR_j1g1
    - Res_DeltaR_j2g1
    - Res_DeltaR_j1g2
    - Res_DeltaR_j2g2
    - Res_DeltaR_jg_min
    - Res_CosThetaStar_CS
    - Res_CosThetaStar_gg
    - Res_CosThetaStar_jj
    - puppiMET_phi
    - puppiMET_pt
    - n_leptons
    - n_jets
    - Res_chi_t0
    - Res_chi_t1
    - Res_DeltaPhi_j1MET
    - Res_DeltaPhi_j2MET
    - VBF_first_jet_eta
    - VBF_first_jet_phi
    - VBF_second_jet_eta
    - VBF_second_jet_phi
    - VBF_first_jet_PtOverM
    - VBF_second_jet_PtOverM
    - VBF_jet_eta_prod
    - VBF_jet_eta_diff
    - VBF_jet_eta_sum
    - VBF_DeltaR_j1b1
    - VBF_DeltaR_j1b2
    - VBF_DeltaR_j2b1
    - VBF_DeltaR_j2b2
    - VBF_DeltaR_j1g1
    - VBF_DeltaR_j1g2
    - VBF_DeltaR_j2g1
    - VBF_DeltaR_j2g2
    - VBF_DeltaR_jb_min
    - VBF_DeltaR_jg_min
    - VBF_dijet_mass
    - Res_HHbbggCandidate_eta
    
    # variables added at preparation level which are not available in HiggsDNA output
    - Res_diphoton_PtOverM_ggjj
    - Res_dijet_PtOverM_ggjj
    # - Res_lead_bjet_pt_over_M_regressed
    # - Res_sublead_bjet_pt_over_M_regressed
    - deltaR_gg
    - Res_lead_bjet_ptPNetCorr_over_M_regressed
    - Res_sublead_bjet_ptPNetCorr_over_M_regressed
